Repository bieniu/nettigo-air-monitor, pull requests merged in 2023-11, with the labels that each got.

#273 Unpin aiohttp
  .github/workflows/test.yml
  requirements.txt
  setup.py
  tox.ini
Labels: bugfix

#279 Use ruff as the code formatter
  .pre-commit-config.yaml
  pyproject.toml
  requirements-test.txt
  tox.ini
Labels: ci

#282 Use aioreponses from master branch
  .github/workflows/test.yml
  requirements-test.txt
  requirements.txt
  tox.ini
Labels: test

#283 Bump aioresponses to version 0.7.6
  requirements-test.txt
Labels: dependencies, python

#284 Add end-of-file-fixer to pre-commit hooks
  .pre-commit-config.yaml
Labels: ci

#285 Fix pre-commit config
  .pre-commit-config.yaml
Labels: bugfix

#286 Update setup script
  requirements-test.txt
  scripts/setup-local-env.sh
Labels: ci
